[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  external_node_modules = [
    "youtubei.js",
    "@bufbuild/protobuf",
    "meriyah"
  ]
  included_files = [
    "views/**",
    "node_modules/ejs/**",
    "node_modules/youtubei.js/**",
    "node_modules/@bufbuild/protobuf/**",
    "node_modules/meriyah/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[images]
  remote_images = [
    "https://i.ytimg.com/.*",
    "https://yt3.ggpht.com/.*"
  ]
