[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[functions]
  included_files = [
    "views/**",
    "node_modules/ejs/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[images]
  remote_images = [
    "https://i.ytimg.com/.*",
    "https://yt3.ggpht.com/.*"
  ]
